### ISSUE TITLE
tabs to left navbar with icons support

### ISSUE THREAD

**Issue by berryma4** [joeatbayes/metadata-forms-gui#2]
svg example link:
https://freeicons.io/icon-list/basic-app-icon-set-v.4

**Comment by joeatbayes** [comment]
Added by supplying leftnav css class for rendering the button. 
![sample-left-navigation](https://user-images.githubusercontent.com/6719216/75614441-bef6d400-5b06-11ea-9954-47c74623919f.jpg)
